# Generated by Django 4.1 on 2023-01-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BodyTemperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pesel", models.CharField(max_length=11)),
                ("measurement", models.DecimalField(decimal_places=2, max_digits=4)),
                ("measurement_date", models.DateField()),
            ],
        ),
    ]
