# Generated by Django 4.1 on 2022-12-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_bodytemperature_doctor_patient_delete_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
