# Generated by Django 4.1 on 2022-12-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_patient_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodytemperature",
            name="measurement_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="creation_date",
            field=models.DateField(),
        ),
    ]
