# Generated by Django 4.1 on 2023-01-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_alter_bodytemperature_measurement_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bodytemperature",
            name="patient_id",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="BodyTemperature",
        ),
    ]
